// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD9n6FECcnmnfAzCTmJAUNXV0B7Zs0Rnc8',
    appId: '1:284130321592:web:f00c7e8ee21fe27b5cc04d',
    messagingSenderId: '284130321592',
    projectId: 'euse-98913',
    authDomain: 'euse-98913.firebaseapp.com',
    storageBucket: 'euse-98913.appspot.com',
    measurementId: 'G-PMP297PP47',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCz7qzZVDdf2NwgksmLVeqzDPRIYECVuc4',
    appId: '1:284130321592:android:2c3553448ba47fdd5cc04d',
    messagingSenderId: '284130321592',
    projectId: 'euse-98913',
    storageBucket: 'euse-98913.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBQmzmJbWPZNNtH8CNiKmqeq6xUfFrt_SI',
    appId: '1:284130321592:ios:d5db66dbc28411bc5cc04d',
    messagingSenderId: '284130321592',
    projectId: 'euse-98913',
    storageBucket: 'euse-98913.appspot.com',
    iosClientId: '284130321592-338nfgmhsu0gief9v7fe8batsdbpdb65.apps.googleusercontent.com',
    iosBundleId: 'com.rounak.euse',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBQmzmJbWPZNNtH8CNiKmqeq6xUfFrt_SI',
    appId: '1:284130321592:ios:7ec780b4d28458865cc04d',
    messagingSenderId: '284130321592',
    projectId: 'euse-98913',
    storageBucket: 'euse-98913.appspot.com',
    iosClientId: '284130321592-2nulu0kpo0a4evigsufdkp5unnad7h0s.apps.googleusercontent.com',
    iosBundleId: 'com.rounak.euse.RunnerTests',
  );
}
